name: Telegram Notify

on:
  push:
  fork:
  watch:
  issues:
    types: [opened, closed, reopened, locked, unlocked]
  issue_comment:
    types: [created, deleted]
  pull_request:
    types: [opened, closed, reopened, locked, unlocked, synchronize]
  pull_request_comment:
    types: [created, deleted]
  release:
    types: [published, released]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify the commit on Telegram
        uses: EverythingSuckz/github-telegram-notify@main
        with:
          bot_token: ${{ 7857754465:AAH97BhQLi5eDsxvK77BzRHXWlVx5BPCCaE }}
          chat_id: ${{ -1002441517237 }}
          topic_id: 121